// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "annotationColor": string;
      "markdownFontSize": string;
      "aiPresets": string;
      "aiProvider": string;
      "aiBaseURL": string;
      "aiApiKey": string;
      "aiModel": string;
      "aiTemperature": string;
      "aiMaxTokens": number;
      "aiSystemPrompt": string;
      "quickActionExplainPrompt": string;
      "quickActionCritiquePrompt": string;
      "quickActionBulletizePrompt": string;
      "quickActionTranslatePrompt": string;
      "quickActionSummarizePrompt": string;
      "mineruApiKey": string;
    };
  }
}
